apiVersion: v1
kind: Service
metadata:
    name: sayalimahabarepensionerdetailservice
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: sayalimahabarepensionerdetailservice